GetUserPosition();

//ALGO
/*
DEBUT

RECUPERER POSITION COURANTE DE L'UTILISATEUR
AFFICHER POINT DE REPERE SUR LA CARTE
QUAND ENREGISTREMENT INCIDENT RECUPERATION DE LA POSITION
LATINCIDENT <- POSTION COURANTE . LATITUDE
CREATION CHAMP CACHE LATITUDE
LONGINCIDENT <- POSITION COURANTE . LONGITUDE
CREATION CHAMP CACHE LONGITUDE
 */

function GetUserPosition(){
    navigator.geolocation.getCurrentPosition(newPosition);
}



